version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000
    depends_on:
      - backend

  testmicroservice:
    build: ./testmicroservice
    ports:
      - "3500:3500"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:[ID BUraya]@db.hjbqpafgpmbxxzsewiql.supabase.co:5432/
      - SUPABASE_URL=https://[URL'nizi buraya yazın].supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5.......